version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres-tesouro
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - docker-network

  cacatesouro:
    build: .
    container_name: cacatesouro
    ports: 
      - '8080:8080'
    depends_on: 
      - db
    networks:
      - docker-network

networks:
  docker-network:

volumes:
  pgdata: