server:
  error:
    include-stacktrace: on_param

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/aerocompany?createDatabaseIfNotExist=true
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#
#  datasource:
#    url: jdbc:h2:mem:aerocompany
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect


spring:
  datasource:
#    url: jdbc:postgresql://database-1-tesouro.crofqb62zw3n.us-east-1.rds.amazonaws.com:5432/tesouro
    url: jdbc:postgresql://localhost:5432/tesouro
    username: postgres
#    password: root1234
    password: root
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  jackson:
    serialization.write_dates_as_timestamps: false